### ISSUE TITLE
No Translation Provided

### ISSUE THREAD

**Issue by Communard1871** [InfinityMods/TowerOfDeception#3]
Hi,
I'm getting the error 
ERROR: No translation provided for @29
[tod/Dialog/va#gulin.d]  ERROR at line 27 column 1-23
Near Text: @29
    Not_found
ERROR: parsing [tod/Dialog/va#gulin.d]: Not_found
ERROR: compiling [tod/Dialog/va#gulin.d]!
When trying to install it with PI

**Comment by ALIENQuake** [comment]
@Communard1871 My mistake, sorry. Fixed by https://github.com/InfinityMods/TowerOfDeception/releases/tag/v4.0.5.
